server:
  port: ${PORT}

#spring:
#  application:
#    name: ${CONFIG_APPLICATION_NAME}
#  profiles:
#    active: ${PROFILE}
#  cloud:
#    config:
#      label: main
#      username: ${SecurityUserName}
#      password: ${SecurityPassword}
#  config:
#    import: optional:configserver:${ConfigServerURI}
#encrypt:
#  key: ${EncryptKey}

keys:
  jwt: "0YNefE6vfwDdYNjNRcv1FWBZUQdqFs91"


spring:
  cloud:
    config:
        enabled: false
  data:
    redis:
      url: redis://redis-cache:6379

#management:
#  endpoints:
#    web:
#      exposure:
#        include: refresh


serviceUrls:
  bookSearch: "http://localhost:8001"
  recommendation: "http://localhost:8002"
  aggregate: "http://localhost:8003"
  gamification: "http://localhost:8004"
  user: "http://localhost:8005"
  client: "http://localhost:8006"
  redis: "redis://redis-cache:6379"

endpoints:
  booksearch:
    base: "/book"
    search: "/book/search" #/search?query=params&here=true
  gamification:
    base: "/"
    login: "/login"
    saveChallenge: "/gamification/challenge"
    badges: "/gamification/badges"
  user:
    base: "/users/"
    login: "/users/login" #/login/:clerkId
    library: "/users/library"
    friends: "/users/friends"
    booksave: "/users/books"
    signup: "/users/signup"
  recommendation:
    base: "/"
    recommend: "/recommend"

urls:
  googlebooks: "https://www.googleapis.com/"