server:
  port: ${PORT}

spring:
  application:
    name: aggregate_service
  profiles:
    active: ${PROFILE}
  cloud:
    config:
      label: main
      username: ${SecurityUserName}
      password: ${SecurityPassword}
  config:
    import: optional:configserver:${ConfigServerURI}
encrypt:
  key: ${EncryptKey}